-- Run this in the Supabase SQL Editor to create all required tables

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'staff',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  contact TEXT NOT NULL,
  plan TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active',
  joined_date DATE,
  expiry_date DATE,
  address TEXT DEFAULT '',
  membership_expiry DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS check_in_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id TEXT NOT NULL,
  member_name TEXT NOT NULL,
  plan TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Active',
  checked_in_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT PRIMARY KEY CHECK (id = 1),
  gym_name TEXT NOT NULL DEFAULT 'NeoFit Fitness Gym',
  contact TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  announcement TEXT NOT NULL DEFAULT ''
);

-- Seed default settings
INSERT INTO settings (id, gym_name, contact, address, announcement)
VALUES (1, 'NeoFit Fitness Gym', '', '', '')
ON CONFLICT (id) DO NOTHING;

-- Note: Default admin user (admin@neofit.com / admin123) is auto-seeded by the server on first startup.
